- name: adjust network socket buffer size of linux system
  hosts: kube-cluster
  become: true
  tasks:
  - name: set net.core.rmem_max
    sysctl:
      name: net.core.rmem_max
      value: 26214400
      sysctl_file: /etc/sysctl.conf
      reload: yes
  - name: set net.core.rmem_default
    sysctl:
      name: net.core.rmem_default
      value: 26214400
      sysctl_file: /etc/sysctl.conf
      reload: yes

